### ISSUE TITLE
class info

### ISSUE THREAD

**Issue by abhishek7467** [pragati21p/Object-Recognition-in-Deep-Learning#1]
how to verify class from the output of the model like I got the result on the running the model
result = model.predict(image)
print(result)
1/1 [==============================] - 0s 54ms/step
[[6.1775843e-04 8.4229231e-01 1.3495189e-04 7.2635207e-03 1.4969152e-01]]

how to verify from the above result the current image is belongs to which class like this is bed, this is sofa, this is chair etc.

**Comment by pragati21p** [comment]
There are 5 classes so its returning 5 scores(corresponding to each class). It belongs to the class with Highest score.
